## 01. NumPy

- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨


### 1-1. nbarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [114]:
import numpy as np

In [115]:
# nbarry의 생성
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조 : {a.shape}")
print(f"배열의 구조 : {b.shape}")

# 배열의 차원 수
print(f"배열의 차원 수 : {a.ndim}")
print(f"배열의 차원 수 : {b.ndim}")

# 데이터 타입
print(f"배열의 데이터 타입 : {a.dtype}")
print(f"배열의 데이터 타입 : {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입 : {new_a.dtype}")

배열의 구조 : (2, 3)
배열의 구조 : (3,)
배열의 차원 수 : 2
배열의 차원 수 : 1
배열의 데이터 타입 : int64
배열의 데이터 타입 : float64
수정한 배열의 데이터 타입 : float64


In [116]:
# 3차원 행렬
a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 수 : {a.ndim}")

배열의 구조 : (3, 2, 3)
배열의 차원 수 : 3


In [117]:
# 4차원 행렬
a = np.array([[[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]],
              [[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]]])

print(f"배열의 구조 : {a.shape}")
print(f"배열의 차원 수 : {a.ndim}")

배열의 구조 : (2, 3, 2, 3)
배열의 차원 수 : 4


### 1-2. 배열 초기화

In [118]:
# 모든 요소가 0인 배열 생성
np.zeros((3, 4)) # 2차원
np.zeros((2, 3, 4), dtype=np.int64) # 3차원


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [119]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [120]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2, 3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [121]:
# 주어진 값으로 채운 배열
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [122]:
# 단위 행렬
np.eye(3, 3)
np.eye(3, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### 1-3. 범위 기반 배열 생성

In [123]:
# arange : range()와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [124]:
# linspace : 시작부터 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 1-4. 랜덤 배열 생성

In [125]:
# random.rand(m, n) : 0 ~ 1 사이의 난수로 초기화
np.random.rand(2, 3)

array([[0.02116519, 0.75046461, 0.17604213],
       [0.45851421, 0.51312271, 0.48402089]])

In [126]:
# random.randn(m, n) : 표준 정규분포를 따르는 난수로 초기화
# 표준 정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(2, 4, 5)

array([[[-0.31946926,  0.33833142, -0.29545257,  1.6557678 ,
         -0.96330814],
        [-0.2088667 , -0.68619642, -0.27309799, -0.40506969,
          0.20672388],
        [ 0.34427065, -1.37215867,  0.979461  , -1.2967198 ,
         -0.55064676],
        [ 1.12348185, -0.49411903,  1.32066894, -0.31387981,
          0.98649149]],

       [[ 0.72101121, -0.53122744,  0.05561497,  1.72958494,
         -1.18899192],
        [ 0.59830942,  0.80256595, -0.40177066, -0.10296417,
         -0.18296753],
        [-0.08712187,  0.85484213,  0.24269165, -0.28959963,
         -0.33899129],
        [-0.06880809, -0.4396162 ,  0.69501598, -0.93446509,
          1.35481799]]])

In [127]:
# random.randint(low, high, (size)) : low이상 high미만의 숫자로 size 형태의 정수 배열을 생성
np.random.randint(10, 20, (2, 4))

array([[11, 19, 14, 19],
       [10, 11, 17, 19]], dtype=int32)

In [128]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(30)
np.random.randn(2, 3)

array([[-1.26405266,  1.52790535, -0.97071094],
       [ 0.47055962, -0.10069672,  0.30379318]])

In [129]:
# RNG(Random Number Generator) : 최근 NumPy 사용에서 권장되는 방식
from numpy.random import default_rng

rng = default_rng(seed=42)
rng2 = default_rng(seed=10)

print(rng.random((3, 2)))
print(rng2.random((3, 2)))
print(rng.integers(2, 10, size=3))
print(rng2.integers(2, 10, size=3))
print(rng.normal(0, 1, size=(2, 2)))
print(rng2.normal(0, 1, size=(2, 2)))
print(rng.uniform(5, 10, size=3))
print(rng2.uniform(5, 10, size=3))

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[0.95600171 0.20768181]
 [0.82844489 0.14928212]
 [0.51280462 0.1359196 ]]
[7 8 7]
[5 7 5]
[[-0.01680116 -0.85304393]
 [ 0.87939797  0.77779194]]
[[ 0.47518364 -0.4507686 ]
 [-0.75493228 -0.81481411]]
[8.2193256  9.11380807 7.21707099]
[7.87880274 8.76650932 9.13551969]


## 실습1. 배열 초기화 및 생성

In [130]:
# 1. 0으로 채워진 크기 (3, 4)배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요
np.zeros([3, 4])
np.full((3,4), 5)

# 해설
a1 = np.zeros((3, 4))
a1_2 = np.full((3, 4), 5)
print("문제 1 :", a1, a1_2, sep="\n")

문제 1 :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [131]:
# 2. 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요
np.arange(0, 21, 2)

# 해설
a2 = np.arange(0, 21, 2)
print("\n문제 2 :", a2)


문제 2 : [ 0  2  4  6  8 10 12 14 16 18 20]


In [132]:
# 3. 0 ~ 1 사이의 실수 난수를 가지는 (2, 3)크기의 배열을 생성하세요
np.random.rand(2, 3)

# 해설
a3 = np.random.rand(2, 3)

print("\n문제 3 : ", a3)


문제 3 :  [[0.51817635 0.76685511 0.93385014]
 [0.08970338 0.19577126 0.99419368]]


In [133]:
# 4. 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요     
print(rng.normal(100, 20,size=(6)))

# 해설 
a4 = np.random.normal(100, 20, 6)
print("\n문제 4 :", a4)

[ 82.81415074 107.37501568  80.82234798 117.56900603  99.00148178
  96.30275273]

문제 4 : [ 84.71904347  84.49622981 127.67694331 115.2077017   94.28708972
 110.76734953]


In [134]:
# 5. 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요.
a = np.arange(1, 21)
a.shape = (4, 5)
print(a)

# 해설
a5 = np.arange(1, 21).reshape(4, 5)
print("\n문제 5 :", a5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

문제 5 : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [135]:
# 6. 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변화하세요

a = np.linspace(0, 1, 12)
a.shape = (3, 4)

print(a)

# 해설
a6 = np.linspace(0, 1, 12).reshape(3, 4)
print("\n문제 6 :", a6)

[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]

문제 6 : [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


In [136]:
# 7. 0 ~ 99 사이의 난수로 이루어진 (10, 10) 배열을 생성한 뒤
# np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.
np.random.seed(10)

a = np.random.randint(0, 99, (10, 10))
b = np.eye(10)

print(a)
print(a + b)

# 해설
a7 = np.random.randint(0, 100, (10, 10))
a7_eye = np.eye(10)
a7_add = a7 + a7_eye
print("\n문제 7 :", a7_add)

[[ 9 15 64 28 89 93 29  8 73  0]
 [40 36 16 11 54 88 62 33 72 78]
 [49 51 54 77 69 13 25 13 92 86]
 [30 30 89 12 65 31 57 36 27 18]
 [93 77 22 23 94 11 28 74 88  9]
 [15 18 80 71 88 11 17 46  7 75]
 [28 33 84 96 88 44  5  4 71 88]
 [88 50 54 34 15 77 88 15  6 85]
 [22 11 12 92 96 62 57 79 42 57]
 [97 50 45 40 89 73 37  0 18 23]]
[[10. 15. 64. 28. 89. 93. 29.  8. 73.  0.]
 [40. 37. 16. 11. 54. 88. 62. 33. 72. 78.]
 [49. 51. 55. 77. 69. 13. 25. 13. 92. 86.]
 [30. 30. 89. 13. 65. 31. 57. 36. 27. 18.]
 [93. 77. 22. 23. 95. 11. 28. 74. 88.  9.]
 [15. 18. 80. 71. 88. 12. 17. 46.  7. 75.]
 [28. 33. 84. 96. 88. 44.  6.  4. 71. 88.]
 [88. 50. 54. 34. 15. 77. 88. 16.  6. 85.]
 [22. 11. 12. 92. 96. 62. 57. 79. 43. 57.]
 [97. 50. 45. 40. 89. 73. 37.  0. 18. 24.]]

문제 7 : [[ 4. 29. 16. 84. 82. 14. 51. 79. 17. 50.]
 [53. 26. 48. 17. 32. 81. 80. 41. 90. 12.]
 [30. 81. 18. 16.  0. 31. 73. 64. 38. 22.]
 [96. 66. 67. 63. 95. 99. 27. 82. 62. 77.]
 [48. 93. 75. 86. 38. 11. 21. 33. 95. 43.]
 [88. 96. 73. 4

In [137]:
# 8. 0 ~ 9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요
np.random.randint(0, 9, (2, 3, 4))

# 해설
a8 = np.random.randint(0, 9, (2, 3, 4))

print("\n문제 8 :", a8)



문제 8 : [[[6 0 4 6]
  [4 8 0 7]
  [1 7 1 1]]

 [[5 5 0 8]
  [3 7 1 5]
  [2 3 4 5]]]


### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- python의 시퀀스보다 빠름

In [138]:
# 인덱싱
a = np.array([10, 20, 30, 40, 50])
print(a[2])
print(a[-1])

30
50


In [139]:
# 다차원 인덱싱
# 파이썬 리스트
matrix = [[1, 2, 4], [4, 5, 6]]
print("파이썬 인덱싱", matrix[1][1])

# numpy배열
a2 = np.array([[1, 2, 4], [4, 5, 6]])
print("numpy 인덱싱 :", a2[1, 1])

# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2, 3, 4)
print(a3)
print("3차원 인덱싱 :", a3[1, 1, 1])

파이썬 인덱싱 5
numpy 인덱싱 : 5
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3차원 인덱싱 : 17


In [140]:
# 슬라이싱
# arr[행_슬라이스, 열_슬라이스]
# 다차원 슬라이스 : arr[..., 4차원 슬라이스, 3차원 슬라이스, 2차원 슬라이스, 1차원 슬라이스]

a1 = np.array([10, 20 ,30, 40, 50])
print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [141]:
# 파이썬 리스트와의 차이
# Python 슬라이스
py_list = [10, 20, 30, 40, 50]
sliced = py_list[1:4]
sliced[1] = 100
print("py원본 :", py_list)
print("py슬라이싱", sliced)
print()
# NumPy 슬라이스
np_list = np.array([10, 20, 30, 40, 50])
np_sliced = np_list[1:4]
np_sliced[1] = 100
print("numpy원본 :", np_list)
print("numpy슬라이싱 :", np_sliced)

py원본 : [10, 20, 30, 40, 50]
py슬라이싱 [20, 100, 40]

numpy원본 : [ 10  20 100  40  50]
numpy슬라이싱 : [ 20 100  40]


## 실습 2. 인덱싱과 슬라이싱

In [142]:
# 1. 다음 배열에서 2, 4, 6번째 요소를 Fancy Indexing으로 선택하세요.
arr = np.arange(10, 30, 2)
arr1 = arr[1:6:2]
print("문제 1 :", arr1)
print()

# 2. 3 x 3 배열에서 왼쪽 위 -> 오른쪽 아래 대각선 요소만 인덱싱으로 추출하세요
arr = np.arange(1, 10).reshape(3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("문제 2 :", arr[0, 0], arr[1, 1], arr[2, 2])
print()

# 3. 3 x 4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요.
arr = np.arange(1, 13).reshape(3, 4)
arr[:,-1] = -1
print("문제 3 :\n", arr)
print()

# 4. 4 x 4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요
arr = np.arange(1, 17).reshape(4, 4)
print("문제 4-1 :\n", arr[::-1],"\n")
print("문제 4-2 :\n", arr[::, ::-1])

문제 1 : [12 16 20]

문제 2 : 1 5 9

문제 3 :
 [[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]

문제 4-1 :
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]] 

문제 4-2 :
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [143]:
# 2차원 배열 슬라이싱

a2 = np.arange(1, 21).reshape(4, 5)
print(a2)

# 행 슬라이싱
print(a2[0]) # [1 2 3 4 5]
print(a2[1]) # [ 6  7  8  9 10]
print(a2[1:3]) # [[ 6  7  8  9 10] [11 12 13 14 15]]
print(a2[2:],'\n') # [[11 12 13 14 15] [16 17 18 19 20]] 

# 열 슬라이싱
print(a2[:, 2]) # [ 3  8 13 18]
print(a2[:, -1]) # [ 5 10 15 20]
print(a2[:, 1:3], '\n') # [[ 2  3] [ 7  8] [12 13] [17 18]] 

# 행과 열 슬라이싱
print(a2[1:3, 2:4]) # [[ 8  9] [13 14]]



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[11 12 13 14 15]
 [16 17 18 19 20]] 

[ 3  8 13 18]
[ 5 10 15 20]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]] 

[[ 8  9]
 [13 14]]


In [144]:
# 3차원 슬라이싱
a3 = np.arange(36).reshape(3, 3, 4)
print(a3)
print(a3[1, 1, 1:3]) # [17 18]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
[17 18]


In [145]:
# 얕은 복사 : 복사본이 원본과 메모리를 공유 -> 변경사항이 서로에게 영향을 줌

a1 = np.array([1, 2, 3])
a1_viewd = a1.view()
a1_viewd[1] = 10
print("원본", a1)              # 원본 [ 1 10  3]
print("복사본", a1_viewd,'\n') # 복사본 [ 1 10  3]

# 깊은 복사 : 복사본이 원본과 독립적으로 복사됨 -> 서로 영향 x
a2 = np.array([1, 2, 3])
a2_copied = a2.copy()
a2_copied[1] = 10
print("원본", a2)           # 원본 [1 2 3]
print("복사본", a2_copied)  # 복사본 [ 1 10  3]

원본 [ 1 10  3]
복사본 [ 1 10  3] 

원본 [1 2 3]
복사본 [ 1 10  3]


In [146]:
# Fancy Indexing
# 정수 배열을 사용하여 여러 인덱스로 여러 요소를 한번에 선택( 앞이 행, 뒤가 열)
af = np.arange(1, 21)
print(af)               # [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
print(af[[4, 7, 11]])   # [ 5  8 12]

af2 = np.arange(1, 21).reshape(4, 5)
print(af2)
print(af2[[1,3], [2,4]]) # [ 8 20]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 5  8 12]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 8 20]


In [147]:
# Boolean Indexing
ab = np.linspace(10, 100, 10)
print(ab)           # [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
print(ab[ab > 40])  # [ 50.  60.  70.  80.  90. 100.]
print()

#Blooean masking
ab2 = np.arange(0, 21)
print(ab2)          # [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
mask = ab2 % 2 == 0
print(mask)         # [ True False  True False  True False  True False  True False  True False  True False  True False  True False  True False  True]
print(ab2[mask])    # [ 0  2  4  6  8 10 12 14 16 18 20]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [152]:
# 실습 1. 인덱싱과 슬라이싱
# 5. 4 x 5 배열에서 가운데 2 x 3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열을 만드세요
arr = np.arange(1, 21).reshape(4, 5)
arr_copied = arr.copy()
print(arr)
print("문제 5 - 부분배열\n", arr_copied[1:3, 1:4],'\n')


# 6. 3 x 4 배열에서 짝수이면서 10 이상인 값만 선택하세요
arr = np.array([[4, 9, 12, 8], [10, 15, 18, 3], [2, 14, 6, 20]])
arr_1 = arr >= 10
arr_2 = arr % 2 == 0
arr_3 = arr[(arr_1) & (arr_2)]
print("문제 6 :", arr_3, '\n')

# 7. 5 x 5 배열에서 2, 4번째 행을 선택하고, 선택된 행에서 열 순서를 [4, 0, 2]로 재배치 하세요
arr = np.arange(1, 26).reshape(5, 5)
arr_1 = arr[[1, 3]]
print("문제 7 :\n", arr_1[:, [4, 0, 2]])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
문제 5 - 부분배열
 [[ 7  8  9]
 [12 13 14]] 

문제 6 : [12 10 18 14 20] 

문제 7 :
 [[10  6  8]
 [20 16 18]]


In [191]:
# 실습 1. 인덱싱과 슬라이싱
# 8. 5 x 3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택하세요
arr = np.array([[10, 20, 30], [55, 65, 75], [40, 45, 50], [70, 80, 90], [15, 25, 35]])
print("문제 8 :\n", arr[arr[:, 0] >= 50], '\n')

# 9. 4 x 4 배열에서 (0, 1), (1, 3), (2, 0), (3, 2) 위치의 요소를 한번에 선택하세요
arr = np.arange(1, 17).reshape(4, 4)
print("문제 9. :", arr[[0, 1, 2, 3], [1, 3, 0, 2]], '\n')

# 10. 3차원 배열 (2, 3, 4)에서 모든 블록 두 번째 열만 추출해 새로운 2차원 배열 (2, 3)을 만드세요
arr3d = np.arange(24).reshape(2, 3, 4)
arr2d = arr3d[:, :, 1]
arr2d.reshape(2, 3)
print("문제 10 :\n", arr2d)

문제 8 :
 [[55 65 75]
 [70 80 90]] 

문제 9. : [ 2  8  9 15] 

문제 10 :
 [[ 1  5  9]
 [13 17 21]]


In [340]:
# 실습 2. NumPy 종합연습
# 문제 1. 0부터 24까지 정수를 가진 배열을 만들고, (5, 5) 
# 배열로 변환한 뒤 가운데행(3번째행)과 가운데열(3번째열)을 각각 1차원 배열로 출력하세요.
arr = np.arange(25).reshape(5, 5)
print(f"문제 1.\n 가운데 행 : {arr[2]}\n 가운데 열 : {arr[:, 2]}")

# 문제 2. 0 ~ 99 난수로 이루어진 (10, 10) 배열을 생성하고 짝수 인덱스의 행만 선택하여 출력하세요.
arr = np.random.randint(0, 99, (10, 10))
print(f"문제 2. \n 짝수 인덱스행 :\n{arr[::2]}\n")

# 문제 3. 0부터 49까지 정수를 가진 배열을 (5, 10) 배열로 변환한 후 
# 2행 3열부터 4행 7열까지의 부분 배열을 추출하세요.
arr = np.arange(0,50).reshape(5, 10)
print(f"문제 3.\n부분배열 :\n {arr[1:4, 2:8]}")

문제 1.
 가운데 행 : [10 11 12 13 14]
 가운데 열 : [ 2  7 12 17 22]
문제 2. 
 짝수 인덱스행 :
[[83 41 78 52  7 13 82  0 66 27]
 [96 23 69 78 57 21 34 81 86 44]
 [51 38  9 52 86 33 49  3 72 54]
 [87 68 76  9 45 12 50 58 80 60]
 [73  6 52 25 62 43 52 80 92 91]]

문제 3.
부분배열 :
 [[12 13 14 15 16 17]
 [22 23 24 25 26 27]
 [32 33 34 35 36 37]]


In [350]:
# 실습 2. NumPy 종합연습
# 문제 4. 0 ~ 9 난수로 이루어진 (4, 4)배열을 생성하고, 각각 인덱싱으로 추출해 출력하세요(for 이용)
# 주대각선 요소(왼쪽 위 -> 오른쪽 아래)
# 부대각선 요소(오른쪽 위 -> 왼쪽 아래)

arr = np.random.randint(0, 10, (4, 4))
print("문제 4.")
print("\n주대각선:", end=" ")
for i in range(len(arr)):
    print(f"{arr.dtype}({arr[i, i]})", end=" ")

print("\n부대각선:", end=" ")
for i in range(len(arr)):
    print(f"{arr.dtype}({arr[i, len(arr)-1-i]})", end=" ")

# 문제 5. 0 ~ 9 난수로 이루어진 (3, 4, 5) 3차원 배열을 생성하고, 두 번째 증에서
#  첫 번째 행과 마지막 열의 값을 출력하세요.
arr = np.random.randint(0, 10, (3, 4, 5))
print('\n\n', arr)
print(f"\n\n문제 5.\n두 번째 층의 첫 행 마지막 열 값 : {arr[1, 0, -1]}")

문제 4.

주대각선: int32(9) int32(1) int32(0) int32(6) 
부대각선: int32(9) int32(2) int32(0) int32(8) 

 [[[4 2 5 1 6]
  [0 7 7 3 9]
  [4 0 2 5 7]
  [4 1 5 3 3]]

 [[2 4 6 1 6]
  [9 2 5 5 6]
  [5 5 4 3 7]
  [2 0 0 0 3]]

 [[8 8 5 1 6]
  [8 6 9 6 6]
  [2 0 4 3 3]
  [3 8 3 4 9]]]


문제 5.
두 번째 층의 첫 행 마지막 열 값 : 6


In [304]:
# 실습 2. NumPy 종합 연습
# 문제 6. 35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10 x 4행렬로 변환 후 출력해주세요
arr = np.arange(35, 75)
arr_1 = arr.reshape(10, 4)
print("문제 6 .\n", arr_1, '\n')

# 문제 7. 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력해주세요.
print("문제 7. \n", arr_1[::-1], '\n')

# 문제 8. 6번에서 만든 배열 중 두번째 행부터 마지막 직전 행까지, 세번째 열부터 마지막 열까지 슬라이싱해서 출력

print("문제 8. \n", arr_1[1:-1, 2:], '\n')

문제 6 .
 [[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]] 

문제 7. 
 [[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]] 

문제 8. 
 [[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]] 



In [358]:
# 실습 2. NumPy 종합 연습
# 문제 9. 1부터 50까지의 난수로 된 5 x 6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성하세요.
arr = np.random.randint(1, 51, (5, 6))
print("문제 9.\n짝수만 : ", arr[arr % 2 == 0], '\n')
print("문제 9.\n짝수만 : ", (lambda arr :arr[arr % 2 == 0])(np.random.randint(1, 51, (5, 6))), '\n')

# 문제 10. 0부터 99까지의 정수로 이루어진(10, 10) 배열을 생성한후, [1, 3, 5]번째 행과[2, 4, 6]번째 열의
# 교차하는 원소들만 선택하여 출력하세요.
arr = np.arange(0, 100).reshape(10, 10)
print("문제 10.\n선택된 원소들 :\n", arr[[1, 3, 5]][:, [2, 4, 6]], '\n')
print("문제 10.\n선택된 원소들 :\n", (lambda arr : arr[[1, 3, 5]][:, [2, 4, 6]])(np.arange(0, 100).reshape(10, 10)), '\n')

# 문제 11. 0 ~ 9 난수로 이루어진 1차원 배열(길이15)을 생성하고, 짝수 인덱스 위치에 있는 
# 값들 중에서 5이상인 값만 선택해 출력하세요
arr = np.random.randint(0, 10, 15)
arr_1 = arr[arr % 2 == 0]
print("문제 11.\n짝수 인덱스 값들 : ", arr_1)
print("짝수 인덱스 중 5 이상인 것들 : ", arr_1[arr_1 >= 5])

문제 9.
짝수만 :  [32 34 38 26 12 16 42 36  8 48 18 30 40 36 18 14 12  8] 

문제 9.
짝수만 :  [34  4 38 14 30 48 24  4 32 42 40 28 44] 

문제 10.
선택된 원소들 :
 [[12 14 16]
 [32 34 36]
 [52 54 56]] 

문제 10.
선택된 원소들 :
 [[12 14 16]
 [32 34 36]
 [52 54 56]] 

문제 11.
짝수 인덱스 값들 :  [2 6 2 8 4 8 8 0]
짝수 인덱스 중 5 이상인 것들 :  [6 8 8 8]
