## 02. NumPy

### 2-1 NumPy 배열 연산



In [1]:
import numpy as np

In [2]:
# 배열 간 연산(1차원)
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(a1 + a2)      # [5 7 9]
print(a1 - a2)      # [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [3]:
# 배열 간 연산(2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + a2)
print(a2 - a1)


[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[10 10]
 [10 10]]


In [4]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1, 2, 3, 4])
print(a1 + 10)      # [11 12 13 14]
print(a1 * 2)       # [2 4 6 8]

[11 12 13 14]
[2 4 6 8]


In [5]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [6]:
# 배열의 구조가 다를 경우
a1 = np.array([1, 2])
a2 = np.array([1, 2, 3])
# print(a1 + a2) # 크기가 다르기 때문에 에러 발생

In [7]:
# 브로드 캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1, 2, 3],
               [4, 5, 6]])  # (2, 3)
a2 = np.array([10, 20, 30]) # 길이가 3인 1차원 배열 (3,)

# 1차원 길이 3
[10, 20 ,30]

# 2차원으로 변현 (1, 3)
[[10, 20, 30]]

# 2차원의 행이 2 -> 2로 확장
[[10, 20, 30],
 [10, 20, 30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [8]:
# 브로드 캐스팅 예제
a1 = np.array([[1], [2], [3]]) # (3, 1)
a2 = np.array([10, 20, 30])    # (3, )

# 과정
# a2 : (3, ) -> (1, 3) 변형
[[10, 20, 30]]

# a1과 a2 비교 -> (3, 1), (1, 3)
[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[10, 20, 30], [10, 20, 30], [10, 20, 30]]

print(a1 + a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [9]:
# 실습1. 배열연산(1)
# 1. 다음 배열을 생성하고, 모든 요소에 3을 더하세요.
arr = np.array([1, 2, 3, 4])
print("문제 1: ", arr + 3,'\n')

# 2. 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열을 만드세요.
arr = np.array([[5, 10],
                [15, 20]])
arr_1 = arr * -1
print("문제 2 : ", arr_1, '\n')
# print("문제 2 : \n", (lambda arr : arr * -1)(np.array([[5, 10], [15, 20]])), '\n')

# 3. 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요.
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])
print(" 문제 3-1 : ", arr1 * arr2, '\n',"문제 3-2 : ", arr1 / arr2)

문제 1:  [4 5 6 7] 

문제 2 :  [[ -5 -10]
 [-15 -20]] 

 문제 3-1 :  [ 2  8 18] 
 문제 3-2 :  [2. 2. 2.]


In [10]:
# 4. 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 필요한 값을 더한 결과배열을 브로드 캐스팅으로만드세요.
arr = np.array([[95, 97],
                [80, 85]])
arr_1 = 100 - arr
print("문제 4 :\n ", arr_1,'\n')
# print("문제 4 : \n", (lambda arr : 100 - arr)(np.array([[95, 97], [80, 85]])), '\n')

# 5. 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열을 만드세요.(브로드 캐스팅 이용)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# • 첫 번째행은 10을 곱하고
# • 두 번째행은 100을 곱해야합니다
arr_1 = np.array([[10], [100]])
arr_2 = arr * arr_1
print("문제 5 : \n", arr_2)

문제 4 :
  [[ 5  3]
 [20 15]] 

문제 5 : 
 [[ 10  20  30]
 [400 500 600]]


In [11]:
# 6. 아래배열에서각 행마다 다른 스칼라값을 더하기 위해
# • 1차원 배열을 만들어 브로드 캐스팅 연산을 수행하세요.
# • 첫 번째 행에100, 두 번째 행에200, 세 번째 행에300을 더하세요.
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])
arr_1 = ([100], [200], [300])
print("문제 6 :\n", arr + arr_1)

문제 6 :
 [[110 120]
 [230 240]
 [350 360]]


### 2-2. 통계 함수 및 집계 연산

In [12]:
# 기본 통계 함수

a = np.array([[1, 2, 3], [4, 5, 6]])
print("원소의 합 : ", np.sum(a))                                        # 원소의 합 :  21
print("원소의 평균 : ", np.mean(a))                                     # 원소의 평균 :  3.5
print("원소의 표준 편차 : ", np.std(a))                                 # 원소의 표준 편차 :  1.707825127659933
print("원소의 최대값 / 최소값 : ", np.max(a), np.min(a))                # 원소의 최대값 / 최소값 :  6 1
print("원소의 최대값 / 최소값 인덱스 : ", np.argmax(a), np.argmin(a))   # 원소의 최대값 / 최소값 인덱스 :  5 0

원소의 합 :  21
원소의 평균 :  3.5
원소의 표준 편차 :  1.707825127659933
원소의 최대값 / 최소값 :  6 1
원소의 최대값 / 최소값 인덱스 :  5 0


In [13]:
# 축(axis) 단위 연산
# axis = 0 -> 가장 높은 차원의 기준 -> 행 기준
# 행 기준 : 행을 따라 연산 = 행을 증가시키며 연산(세로 방향)
# axis = 1 -> 가장 높은 차원 기준 -> 열 기준
# 열 기준 : 열을 따라 연산 -> 열을 증가시키며 연산(가로 방향)

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("행 기준합", np.sum(a, axis = 0))         # 행 기준합 [12 15 18]
print("열 기준합", np.sum(a, axis = 1))         # 열 기준합 [ 6 15 24]
print("행 기준 평균", np.mean(a, axis = 0))     # 행 기준 평균 [4. 5. 6.]
print("열 기준 평균", np.mean(a, axis = 1))     # 열 기준 평균 [2. 5. 8.]

행 기준합 [12 15 18]
열 기준합 [ 6 15 24]
행 기준 평균 [4. 5. 6.]
열 기준 평균 [2. 5. 8.]


In [14]:
# 누적 연산
arr = np.array([1, 2, 3, 4])
print("누적 합", np.cumsum(arr))       # 누적 합 [ 1  3  6 10]
print("누적 곱", np.cumprod(arr))      # 누적 곱 [ 1  2  6 24]

누적 합 [ 1  3  6 10]
누적 곱 [ 1  2  6 24]


In [15]:
# 실습 2. 통계 함수 및 집계 연산
# 문제 1. 아래 배열의 합계와 평균을 각각 구하세요
arr = np.array([5, 10, 15, 20])
print(f"문제 1 .\n 전체 합계 : {np.sum(arr)} \n 전체 평균 : {np.mean(arr)}")

# 문제 2. 다음 2차원 배열에서 전체 최소값과 최대값을 구하세요.
arr = np.array([[3, 7, 1],
                [9, 2, 8]])
print(f"문제 2. \n 최소값 : {np.min(arr)} \n 최대값 : {np.max(arr)}")

# 문제 3. 아래 배열에서 각 열의 합계와 각 행의 합계를 각각 구하세요.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(f"문제 3 . \n 열의 합계 : {np.sum(arr, axis = 1)} \n 행의 합계 : {np.sum(arr, axis = 0)}")

문제 1 .
 전체 합계 : 50 
 전체 평균 : 12.5
문제 2. 
 최소값 : 1 
 최대값 : 9
문제 3 . 
 열의 합계 : [ 6 15 24] 
 행의 합계 : [12 15 18]


In [24]:
# 실습 2. 통계 함수 및 집계 연산
# 문제 4. 아래 배열에서 행별 평균과 열별 평균을 각각 구하세요.
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])
print(f"문제 4 . \n 행의 평균 : {np.mean(arr, axis = 0)} \n 열의 평균 : {np.mean(arr, axis = 1)}\n")

# 문제 5. 1차원 배열에서 전체 표준편차를 구하고, 각 요소가 평균으로부터 얼마나 떨어져있는지 편차배열을만드세요. (값 -평균)
arr = np.array([2, 4, 4, 4, 5, 5, 7, 9])
arr_1 = np.std(arr)
print(f"문제 5. \n 표준 편차 : {arr_1} \n 편차 배열 : \n{arr - np.mean(arr)}\n")

# 문제 6. 아래 2차원 배열에서 행 단위 누적 합과 열 단위 누적 곱을 각각 구하세요.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(f"문제 6-1. \n행 단위 누적 합 : \n{np.cumsum(arr, axis = 0)} \n행 단위 누적 곱 : \n{np.cumprod(arr, axis = 0)}")   
print(f"\n문제 6-2. \n열 단위 누적 합 : \n{np.cumsum(arr, axis = 1)} \n열 단위 누적 곱 : \n{np.cumprod(arr, axis = 1)}")    

문제 4 . 
 행의 평균 : [30. 40.] 
 열의 평균 : [15. 35. 55.]

문제 5. 
 표준 편차 : 2.0 
 편차 배열 : 
[-3. -1. -1. -1.  0.  0.  2.  4.]

문제 6-1. 
행 단위 누적 합 : 
[[1 2 3]
 [5 7 9]] 
행 단위 누적 곱 : 
[[ 1  2  3]
 [ 4 10 18]]

문제 6-2. 
열 단위 누적 합 : 
[[ 1  3  6]
 [ 4  9 15]] 
열 단위 누적 곱 : 
[[  1   2   6]
 [  4  20 120]]


### 2-3. 논리 연산과 조건 연산

In [26]:
# np.where()
# 조건 기반 선택 함수

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr > 30, "high", "low")
print(result)           # ['low' 'low' 'low' 'high' 'high']

['low' 'low' 'low' 'high' 'high']


In [30]:
arr = np.array([10, 20, 30, 40, 50])
# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스를 반환
result = np.where(arr > 30)
print(result)           # (array([3, 4]),)
print(arr[result])      # [40 50] Fancy Indexing

(array([3, 4]),)
[40 50]


In [35]:
# 논리 연산
# and : & - 모든 조건이 True여야 True
# or : | - 조건 중에 하나라도 True인 경우 True
# not : ~ - True -> False, False -> True

# &(and) 연산
arr = np.array([10, 20 ,30 , 40, 50])
mask = (arr > 10) & (arr < 50)
print(mask)                        # [False  True  True  True False]
print("& 연산 ", arr[mask])        # & 연산  [20 30 40]

# |(or) 연산
mask_or = (arr < 20) | (arr > 40)
print(mask_or)                     #[ True False False False  True]
print("| 연산", arr[mask_or])       # | 연산 [10 50]

# ~(not) 연산
mask_not = ~ (arr > 30)
print(mask_not)                     # [ True  True  True False False]
print("~ 연산 ", arr[mask_not])     # ~ 연산  [10 20 30]

[False  True  True  True False]
& 연산  [20 30 40]
[ True False False False  True]
| 연산 [10 50]
[ True  True  True False False]
~ 연산  [10 20 30]


In [77]:
# 실습 3. 논리 연산과 조건 연산
# 문제 1. 1차원 배열 [5, 12, 18, 7, 30, 25]에서 10보다 크고 20보다 작은 값만 필터링 하세요
print("문제 1 : ", (lambda arr : arr[(arr > 10) & (arr < 20)])(np.array([5, 12, 18, 7, 30, 25])))

# 문제 2. 배열[10, 15, 20, 25, 30, 35]에서 15 이하이거나 30 이상인 값만 선택하세요.
print("문제 2 : ", (lambda arr : arr[(arr <= 15) | (arr >= 30)])(np.array([10, 15, 20, 25, 30, 35])))

# 문제 3. 배열[3, 8, 15, 6, 2, 20]에서 10 이상인 값을 모두 0으로 변경하세요.
arr = np.array([3, 8, 15, 6, 2, 20])
result = np.where(arr > 10, 0, arr)
print("문제 3 : ", result)

# 문제 4. 배열[7, 14, 21, 28, 35]에서20 이상인 값은"High", 나머지는 "Low"로 표시하는 새로운 배열을 생성하세요.
arr = np.array([7, 14, 21, 28, 35])
result = np.where(arr > 20, "high", "low")
print("문제 4 : ", result)

문제 1 :  [12 18]
문제 2 :  [10 15 30 35]
문제 3 :  [3 8 0 6 2 0]
문제 4 :  ['low' 'low' 'high' 'high' 'high']


In [65]:
# 실습 3. 논리 연산과 조건 연산
# 문제 5. 0 ~ 9 범위의 배열에서 짝수는 그대로 두고, 홀수는 홀수 값 × 10으로 변환한 배열을 만드세요.
arr = np.arange(0, 10)
result = np.where(arr % 2 == 1, arr * 10, arr)
print("문제 5 : ", result)

# 문제 6. 아래 2차원 배열에서 20 이상40 이하인 값만 선택하세요.
print("문제 6 : ", (lambda arr : arr[(arr >= 20) & (arr <= 40)])(np.array([[10, 25, 30],[40, 5, 15],[20, 35, 50]])))

# 문제 7. 배열 [1, 2, 3, 4, 5, 6]에서 3의 배수가 아닌 값만 선택하세요.
print("문제 7 : ", (lambda arr : arr[np.where(arr % 3 != 0)])(np.array([1, 2, 3, 4, 5, 6])))

문제 5 :  [ 0 10  2 30  4 50  6 70  8 90]
문제 6 :  [25 30 40 20 35]
문제 7 :  [1 2 4 5]


In [78]:
# 실습 3. 논리 연산과 조건 연산
# 문제 8. 랜덤정수(0~100) 10개 배열에서 아래와 같이 새로운 배열을 만드세요.
# 50 이상인값은그대로
# 50 미만인값은50으로변경
print("문제 8 : \n", (lambda arr : np.where(arr > 50, arr, 50))(np.random.randint(0, 100, (10, 10))))

# 문제 9. 2차원 배열에서 아래와 같이 분류된 문자열 배열을 생성하세요.
# 70 이상→ "A"
# 30 이상70 미만→ "B"
# 30 미만→ "C"
# [[5, 50, 95],
# [20, 75, 10],
# [60, 30, 85]]

print("문제 9 : \n", (lambda arr : np.where(arr >= 70, "A", np.where((arr >= 30) & (arr < 70), "B", "C")))(np.array([[5, 50, 95], [20, 75, 10], [60, 30, 85]])))

문제 8 : 
 [[87 50 61 50 58 50 50 91 66 50]
 [62 50 50 50 80 50 73 89 50 58]
 [50 68 76 79 50 81 53 50 50 58]
 [88 50 63 61 93 50 50 50 92 79]
 [50 50 50 52 50 67 52 50 89 53]
 [50 56 50 50 97 52 50 75 50 50]
 [50 94 52 52 50 50 77 65 80 76]
 [88 50 77 90 67 69 50 58 50 50]
 [86 50 51 76 50 97 88 50 86 50]
 [50 68 50 80 68 50 50 91 50 50]]
문제 9 : 
 [['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]


### 2-4. 행렬 곱셈
- 두 행렬을 곱해서 새로운 행렬을 생성하는 연산
- 첫 번째 행렬의 열수와 두 번째 행렬의 행수가 같아야 곱셍이 가능함
- np.dot(), np.matmul() 사용

In [80]:
# np.dot(a, b) : 배열의 내적 연산
# 스칼라 연산 (OD)
a = np.array(3)
b = np.array(4)
print(np.dot(a, b))     # 12

12


In [83]:
# 1차원 배열 간 연산 -> 내적
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.dot(a, b))         # 70 : (1 * 5) + (2 * 6) + (3 * 7) + (4 * 8)

# 물건 구매
# 데이터 분석에서 벡터와 배열
c = [1000, 2000, 5000, 10000] # 가격
d = [10, 3, 5, 7]             # 개수

print(np.dot(c, d))     # 111000

70
111000


In [84]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1, 2, 3,], [4, 5, 6]])   # (2, 3)
b = np.array([[1, 2], [3, 4], [5, 6]])  # (3, 2)
print(np.dot(a, b))

[[22 28]
 [49 64]]


In [ ]:
# np.matmul(a, b)
# Matrix Multiplication
# 스칼라 연산 시도시 에러

# 1차원 배열 간 연산 -> 내적
a = np.array([1, 2])
b = np.array([3, 4])
print(np.matmul(a, b))      # 11 : (1 * 3) + (2 * 4)

# 2차원 행렬 간 연산
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # (2, 3)
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])  # (3, 2)
print(np.matmul(a, b)) 
# [[22 28]      # [[1 * 1 + 2 * 3 + 3 * 5, 1 * 2 + 2 * 4 + 3 * 6]  = [[22 28]
#  [49 64]]     # [1 * 4 + 3 * 5 + 5 * 6, 2 * 4 + 4 * 5 + 6 * 6]]  =  [49 64]]

11
[[22 28]
 [49 64]]


In [114]:
# 2차원 1차원 간 연산
c = np.array([[1, 2],
              [3, 4]])         # (2, 2)
d = np.array([5, 6])           # (2, )
print(np.matmul(c, d))         # [17 39]
print(np.matmul(d, c))         # [23 34]

# @ 연산자
e = np.array([[1, 2, 3]])
f = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(np.matmul(e, f))  # [[22 28]]
print(e @ f)            # [[22 28]]

[17 39]
[23 34]
[[22 28]]
[[22 28]]


In [112]:
# 실습 4. 행렬 곱셈
# 문제 1. 1부터 9까지의 정수로 채워진 (3, 3) 배열A와, 모두 2로 채워진 (3, 2) 배열 B를 만들고 곱하세요.
print("문제 1 : \n", (lambda a, b : np.dot(a, b))(np.arange(1, 10).reshape(3, 3), np.full((3,2), 2)),'\n')

# 문제 2. 4 × 4 단위행렬 I와, 4 × 4 난수행렬M(0 ~ 9 사이정수) 간의 곱을 구하고, 결과와 M이 동일한지 확인하세요.
i = np.eye(4, 4)
m = np.random.randint(0, 9, (4, 4))
print("문제 2.\n","M : \n", m)
print("결과 : \n", i @ m)

# 문제 3. 모든 값이 1인 (2, 5) 배열 X와, 5부터 14까지의 연속된 정수로 채워진 (5, 2) 배열 Y를 만들어 곱하세요.
print("문제 3 :\n", (lambda x, y : x @ y)(np.ones((2, 5)), np.arange(5, 15).reshape(5, 2)), '\n')

# 문제 4. 0 이상 5미만의 임의의 정수로 채워진 (3, 2) 배열C와 (2, 3) 배열D를 각각 만들어 곱한 결과의 shape와 값을 출력하세요.
c = np.random.randint(0, 5, (3, 2))
d = np.random.randint(0, 5, (2, 3))
result = c @ d
print(f"문제 4. \n값: \n{result}\nshape : {result.shape}")

문제 1 : 
 [[12 12]
 [30 30]
 [48 48]] 

문제 2.
 M : 
 [[8 5 4 3]
 [5 6 7 7]
 [2 6 8 5]
 [4 7 3 5]]
결과 : 
 [[8. 5. 4. 3.]
 [5. 6. 7. 7.]
 [2. 6. 8. 5.]
 [4. 7. 3. 5.]]
문제 3 :
 [[45. 50.]
 [45. 50.]] 

문제 4. 
값: 
[[ 4 12 28]
 [ 0  3  4]
 [ 0  9 12]]
shape : (3, 3)
