## 03. NumPy
### 3-1. 배열의 형태 변형과 차원 확장 / 축소

In [2]:
import numpy as np

In [ ]:
# array.ravel()
# - 다차원 배열을 1차원 배열로 펼침
# 결과를 view로 반환(view 변경)

a = np.array([[1, 2, 3], [4, 5, 6]])

flat = a.ravel()
print(flat)         # [1 2 3 4 5 6]

flat[2] = 100
print(flat)         # [  1   2 100   4   5   6]
print(a)            # [[  1   2 100]
                    #  [  4   5   6]]

[1 2 3 4 5 6]
[  1   2 100   4   5   6]
[[  1   2 100]
 [  4   5   6]]


In [9]:
# array.flatten()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 복사본으로 반환 (복사본 병경 시 원본은 변경되지 않음)
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)            #[[[1 2]
                    #  [3 4]
                    #  [[5 6]
                    #   [7 8]]]  

flat = a.flatten()
print(flat)         # [1 2 3 4 5 6 7 8]

flat[4] = 0
print(flat)         # [1 2 3 4 0 6 7 8]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 0 6 7 8]


In [15]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1
a = np.array([[1, 2, 3], [4, 5, 6]])
print("원본 : \n",a,'\n', a.shape)

# axis = 0
a0 = np.expand_dims(a, axis = 0)
print(a0,'\n', a0.shape)
# axis = 1
a1 = np.expand_dims(a, axis = 1)
print(a1,'\n', a1.shape)

# axis = 2
a2 = np.expand_dims(a, axis = 2)
print(a2,'\n', a2.shape)

원본 : 
 [[1 2 3]
 [4 5 6]] 
 (2, 3)
[[[1 2 3]
  [4 5 6]]] 
 (1, 2, 3)
[[[1 2 3]]

 [[4 5 6]]] 
 (2, 1, 3)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] 
 (2, 3, 1)


In [ ]:
# np.squeeze(a, axis)
# - 배열에서 크기가 1인 차원을 제거해주는 함수 (차원 축소)
a = np.array([[[[1], [2], [3]]],[[[1], [2], [3]]]])
print(a.shape)              # (2, 1, 3, 1)

s = np.squeeze(a)
print(s)                    # [[1 2 3]
                            # [1 2 3]]
print(s.shape)              # (2, 3)

(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [ ]:
# axis 지정하는 경우
a2 = np.zeros((1, 4, 1, 2))
print(a2.shape)                 # (1, 4, 1, 2)

s1 = np.squeeze(a2, axis = 0)
print(s1.shape)                 # (4, 1, 2)

s2 = np.squeeze(a2, axis = 2)
print(s2.shape)                 # (1, 4, 2)

# 차원의 크기가 1이 아닌 차원은 제거할 수 없음
# s3 = np.squeeze(a, axis = 1)

(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


In [ ]:
# np.unique()
# - 배열에서 중복된 요소를 제거해줌
a = np.array([1, 1, 1, 5, 5, 2, 2, 2, 2, 4, 4, 4, 3, 3, 3])
u1 = np.unique(a) # 고유값의 오름차순 배열을 반환
print(u1)         # [1 2 3 4 5]

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스 : ", idx)                 # 인덱스 :  [ 0  5 12  9  3]
print("원본의 고유값 인덱스 : ", inv)    # 원본의 고유값 인덱스 :  [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
print("값의 등장 횟수 : ", cnt)         # 값의 등장 횟수 :  [3 4 3 3 2]

[1 2 3 4 5]
인덱스 :  [ 0  5 12  9  3]
원본의 고유값 인덱스 :  [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수 :  [3 4 3 3 2]


In [ ]:
# 실습 1. 배열 형태 변형, 차원 확장·축소(1)
# 1. 아래의 배열을 사용해서
arr = np.array([[10, 20], [30, 40], [50, 60]])
# 1) ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
# 2) arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와flatten 결과에 어떤 변화가 있는지 확인하세요.
a1 = np.ravel(arr)
a2 = arr.flatten()
arr[0, 0] = 999
# a2[0] = 999
print("문제 1 ravel. \n", a1,'\n', a1.shape)
print("문제 1 flatten. \n", a2,'\n', a2.shape)

# 2. 크기가 32 x 32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여 shape (1, 32, 32)로
#  바꾸는코드를작성하세요.
img = np.random.rand(32, 32)
img_1 = np.expand_dims(img, axis=0)
print("문제 2.\n", img_1, img_1.shape)

문제 1 ravel. 
 [999  20  30  40  50  60] 
 (6,)
문제 1 flatten. 
 [10 20 30 40 50 60] 
 (6,)
문제 2.
 [[[0.42358953 0.94492203 0.10627639 ... 0.64925008 0.11797969 0.51824135]
  [0.4082242  0.18220613 0.57627056 ... 0.7930418  0.65104941 0.20514485]
  [0.15410755 0.18495423 0.9443995  ... 0.3734397  0.74193181 0.91797247]
  ...
  [0.41800144 0.55829612 0.45367697 ... 0.31881723 0.83663803 0.66286538]
  [0.66899956 0.90212375 0.95961152 ... 0.02537224 0.96764858 0.66957465]
  [0.29995725 0.40015516 0.08985528 ... 0.53999139 0.88949027 0.12707579]]] (1, 32, 32)


In [69]:
# 실습 1. 배열 형태 변형, 차원확장 · 축소(2)
# 3. 아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
img = np.random.randint(0, 255, (1, 28, 28, 1))
img_1 = np.squeeze(img)
print("문제 3. \n", img_1.shape, '\n')

# 4. 아래 2차원 배열을 1) 1차원 배열로 만든 후 2) 중복값을 제거한 뒤 shape (1, n)으로 재구성 하세요.
arr = np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])
arr_1 = arr.flatten()
arr_1 = np.unique(arr_1)
print("문제 4. \n", arr_1.reshape(1, len(arr_1)))

문제 3. 
 (28, 28) 

문제 4. 
 [[1 2 3 4]]


In [70]:
# 실습 1. 배열 형태 변형, 차원 확장 ·  축소(3)
# 5. 다음 배열을 shape (10,)로 만든 뒤 고유값 배열을 구하세요.
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]]) # shape (1, 10, 1)
arr_1 = np.squeeze(arr)
arr_1_uniq = np.unique(arr)
print("문제 5 : ", arr_1_uniq)

# 6. 다음 배열을 1차원 배열로 만든 후 고유값만 추출해서 shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
arr = np.array([[[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
                [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]]]) # shape (2, 3, 4)
arr_1 = arr.flatten()
arr_1_uniq = np.unique(arr_1)
print("문제 6 .\n", arr_1_uniq.reshape(len(arr_1_uniq), 1))

# resaped = np.expand_dims(arr_1, axis = 1)

문제 5 :  [1 2 3]
문제 6 .
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## 3-2. 배열의 결합과 분리

In [ ]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])

result1 = np.concatenate((a, b), axis = 0)
print(result1, result1.shape)
# [[1 2]
#  [3 4]
#  [5 6]]  (3, 2)

# 결합이 불가 -> 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a, b), axis = 1) # ValueError

c = np.array([[7], [8], [9]])
result3 = np.concatenate((result1, c), axis = 1)
print(result3, result3.shape)
# [[1 2 7]
#  [3 4 8]
#  [5 6 9]] (3, 3)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 7]
 [3 4 8]
 [5 6 9]] (3, 3)


In [ ]:
# np.stack()
# 새로운 차원을 추가하면서 결합
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# axis = 0
s1 = np.stack((a, b), axis=0)
print(s1, s1.shape)
# [[1 2 3]
#  [4 5 6]] (2, 3)

# axis = 1
s2 = np.stack((a, b), axis=1)
print(s2, s2.shape)
# [[1 4]
#  [2 5]
#  [3 6]] (3, 2)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


In [ ]:
# np.hstack / np.vstack
# hstack()
# - 열 방향(가로)으로 결합
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
print(h, h.shape)       # [1 2 3 4 5 6] (6,)

# vstack()
# - 행 방향(세로)으로 결합
v = np.vstack((a, b))
print(v, v.shape)
# [[1 2 3]
#  [4 5 6]] (2, 3)

[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [87]:
# np.split()
# 배열을 여러 개의 하위 배열로 분할
a = np.arange(9)
s = np.split(a, 3)
print(a, '\n', s)
# [0 1 2 3 4 5 6 7 8] 
#  [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
print(s[0])     # [0 1 2]
print(s[1])     # [3 4 5]
print(s[2])     # [6 7 8]

# s2 = np.split(a, 4) ----> 같은 크기로만 나눌 수 있다.(0 ~ 8까지 수를 4등분 불가능)

[0 1 2 3 4 5 6 7 8] 
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [97]:
a = np.arange(16).reshape(4, 4)
print(a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]
s1 = np.split(a, [1, 3])
for part in s1:
    print(part)
# [[0 1 2 3]]
# [[ 4  5  6  7]
#  [ 8  9 10 11]]
# [[12 13 14 15]]   

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [113]:
# 실습2. 배열의 결합과 분리(1)
# 1. 다음 두 배열을 행 방향으로 이어붙이세요.
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])
ab = np.vstack((a, b))
print("문제 1 . \n", ab)
# 2. 아래 배열을 3개로 같은 크기로 분할하세요.
print("문제 2 . \n", (lambda a : np.split(a, 3))(np.arange(12)))
# 3. 다음 배열들을 새로운 축에 쌓아 shape이 (3, 2)인 배열을 만드세요.
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
abc = np.vstack((a, b, c))
print("문제 3. \n", abc, abc.shape)

문제 1 . 
 [[1 2]
 [3 4]
 [5 6]]
문제 2 . 
 [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
문제 3. 
 [[1 2]
 [3 4]
 [5 6]] (3, 2)


In [132]:
# 실습2. 배열의 결합과 분리(2)
# 4. shape가 (2, 3)인 아래 두 배열을shape (2, 2, 3)인 3차원 배열을 만드세요.
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])
ab = np.concatenate((a, b), axis=1).reshape(2, 2, 3)
print("문제 4. \n", ab, ab.shape)

# 5. 아래의 1차원 배열을 2:3:3 비율(총 3개)로 분할하세요.
arr = np.arange(8)
parts = np.array_split(arr, 3)
print("문제 5.")
for idx, part in enumerate(parts, start=1):
    print(f" part{idx} \n {part}")
# 6. 아래 두 배열을 axis=0, axis=1로 각각 stack하여 두 경우의 결과shape을 모두 구하세요
a = np.ones((2, 3))
b = np.zeros((2, 3))
ab1 =np.stack((a, b), axis=0)
print("문제 6 axis=0. \n",ab1, ab1.shape, '\n') 
ab2 =np.stack((a, b), axis=1)
print("문제 6 axis=1. \n", ab2, ab2.shape) 

문제 4. 
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]] (2, 2, 3)
문제 5.
 part1 
 [0 1 2]
 part2 
 [3 4 5]
 part3 
 [6 7]
문제 6 axis=0. 
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] (2, 2, 3) 

문제 6 axis=1. 
 [[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]] (2, 2, 3)


## 3-3 배열의 정렬


In [ ]:
# np.sort(array)
# 정렬된 복사본 반환
# array.sort()
# 원본 배열을 정렬

# 1차원 배열
a = np.array([3, 1, 4, 2])

# 정렬한 배열을 반환
s = np.sort(a)
print(s)        # [1 2 3 4]
print(a)        # [3 1 4 2] 원본 유지

# 원본을 정렬
a.sort()
print(a)        # [1 2 3 4] 원본을 정렬

# 내림차순 : sort한 후 배열을 뒤집어야 함
print(a[::-1])

[1 2 3 4]
[3 1 4 2]
[1 2 3 4]
[4 3 2 1]


In [ ]:
# 2차원 배열 정렬
a = np.array([[6, 5, 4], [3, 1, 2]])
s1 = np.sort(a, axis=0)
print(s1)
# [[3 1 2]
#  [6 5 4]]
s2 = np.sort(a, axis=1)
print(s2)
# [[4 5 6]
#  [1 2 3]]

[[3 1 2]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [143]:
# np.argsort()
# - 정렬 인덱스를 반환

a = np.array([3, 5, 1, 2, 4])
idx = np.argsort(a)
print(idx)
print(a[idx])

[2 3 0 4 1]
[1 2 3 4 5]


In [148]:
# 실습3. 배열의  정렬(1)
# 1. 아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요.
arr = np.array([7, 2, 9, 4, 5])
arr_1 = np.sort(arr)
print(f"문제 1. \n 오름차순 : {arr_1} \n 내림차순 : {arr_1[::-1]}" )
# 2. 아래의 2차원 배열에서 각 행(row) 별로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[9, 2, 5],
                [3, 8, 1]])
arr_1 = np.sort(arr, axis=1)
print("문제 2. \n", arr_1)

문제 1. 
 오름차순 : [2 4 5 7 9] 
 내림차순 : [9 7 5 4 2]
문제 2. 
 [[2 5 9]
 [1 3 8]]


In [ ]:
# 실습3. 배열의  정렬(2)
# 3. 아래의  1차원  배열에서  정렬  결과(오름차순)가 되는  인덱스  배열을  구하고, 그 인덱스를  이용해
#  원본  배열을  직접  재정렬하는코드를  작성하세요.
arr = np.array([10, 3, 7, 1, 9])
arg_arr = np.argsort(arr)
print("문제 3. \n오름차순 인덱스 배열 :", arg_arr)
print("원본 재정렬 : ", arr[arg_arr])
print("원본 : ", arr)

# 4. 아래 2차원 배열을 열(column) 기준(axis=0)으로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[4, 7, 2],
                [9, 1, 5],
                [6, 8, 3]])
arr_0 = np.sort(arr, axis=0)
print("문제 4.\n", arr_0)

문제 3. 
오름차순 인덱스 배열 : [3 1 2 4 0]
원본 재정렬 :  [ 1  3  7  9 10]
원본 :  [10  3  7  1  9]
문제 4
 [[4 1 2]
 [6 7 3]
 [9 8 5]]
