## PyTorch Quiz 2 : 연산

In [2]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
# 여기에 코드를 작성합니다
x = torch.tensor([2, 4, 6])
x = x + 5
x

tensor([ 7,  9, 11])

### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [13]:
# 여기에 코드를 작성합니다
x = torch.rand(3, 3)
y = torch.rand(3, 3)

print(x + y)
print(torch.sub(x, y))
print(x * y)
print(torch.div(x, y))

tensor([[1.9431, 0.7846, 1.5267],
        [1.4473, 0.8135, 0.9408],
        [1.6654, 0.9380, 0.9950]])
tensor([[ 0.0549,  0.3468,  0.4274],
        [-0.3653,  0.2154, -0.3433],
        [ 0.0809,  0.0020, -0.9577]])
tensor([[0.9432, 0.1239, 0.5370],
        [0.4903, 0.1539, 0.1918],
        [0.6918, 0.2200, 0.0182]])
tensor([[1.0581, 2.5838, 1.7775],
        [0.5970, 1.7203, 0.4653],
        [1.1021, 1.0042, 0.0191]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [14]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8], [9, 10], [11, 12]])

print(torch.matmul(a, b))

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [19]:
# 여기에 코드를 작성합니다
r = torch.matmul(a, b)
r = r + 10
print(torch.clamp(r, max=100))

tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [20]:
# 여기에 코드를 작성합니다
m = torch.tensor([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])
print(torch.sum(m, dim=0))

tensor([55, 60, 65, 70, 75])
