In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 1.
data = [1, 2, 3]
ndarray = np.array(data)
ndarray

array([1, 2, 3])

In [ ]:
# 2.
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# 3. 
arr = np.arange(1, 10) * 3
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# 4.
arr = np.arange(2, 1000, 2)
arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [ ]:
# 5. 
arr = np.arange(0, 1, 0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
#6.
data = [0, 1, 2, 3, 4, 5]
arr = np.array(data).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 7.
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(6)
arr.flatten()
print(arr)

[[0 1 2]
 [3 4 5]]


In [ ]:
# 8.

arr = np.arange(3)
arr.reshape(3, 1)
print(arr)

[0 1 2]


In [ ]:
# 9.
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 10. 
arr = np.ones(20, dtype=int)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
# 11.
arr = np.ones(20, dtype=int).reshape(4, 5)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# 12.
arr = np.ones(100, dtype = int).reshape(10,10)
print(arr*255)

[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


In [ ]:
# 13.
arr = np.zeros((3, 4), dtype= int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# 14.
data = [1, 2, 3]
np.array(data)
np.int32
print(data)

[1, 2, 3]


In [ ]:
# 15.
arr = np.array([1, 2, 3])
print(arr.dtype)


int64


In [ ]:
# 16.
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [ ]:
# 17.
arr = np.array([1, 2, 3])
# arr = np.int16
arr.astype(np.int16)
arr

array([1, 2, 3])

In [ ]:
# 18.
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
arr2 = arr.astype(np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
# 19.
# array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
#         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
#         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
#         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])
arr = np.linspace(0, 10, 20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# 20.
arr = np.arange(9).reshape(3, 3)
# arr[[0 1 2]
#     [3 4 5]
#     [6 7 8]]

arr[:, 1]

array([1, 4, 7])

In [ ]:
# 21.
arr = np.arange(25).reshape(5, 5)
# arr[3:4, 2:3]
# arr[3, 2]
arr[3][2]

np.int64(17)

In [ ]:
# 22.
arr = np.arange(5)
# arr[1:2][3:5]
# arr[1::2]
arr[[1, 3]]

array([1, 3])

In [ ]:
# 23.
arr = np.arange(25).reshape(5, 5)
# arr[1, 1:]
arr[1][1:]

array([6, 7, 8, 9])

In [ ]:
# 24.
arr = np.arange(25).reshape(5, 5)
arr2 = arr[1:3, 1:3].reshape(2, 2)
arr2

array([[ 6,  7],
       [11, 12]])

In [ ]:
# 25.
arr = np.arange(25).reshape(5, 5)
arr[[0, -1]][:, [0, 3]]


array([[ 0,  3],
       [20, 23]])

In [ ]:
# 26.
data = [1, 2, 3]
arr = np.array(data) * 10
arr

array([10, 20, 30])

In [ ]:
# 27.
data = [1, 2, 3]
arr = np.array(data) ** 2
arr

array([1, 4, 9])

In [ ]:
# 28. 진짜 몰랐던거!!
data = [1, 2, 3]
arr = np.array(data) ** (0.5) #0.5를 제곱하면 루트다!
arr

array([1.        , 1.41421356, 1.73205081])

In [ ]:
# 29.
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.mean(axis=0, dtype=int)

array([12, 18])

In [ ]:
# 30.
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

score.std(axis=1)

array([5., 1.])

In [ ]:
# 31.
a = np.arange(4).reshape(2, 2)
b = np.arange(1, 5).reshape(2, 2)

# a @ b
np.matmul(a, b)

array([[ 3,  4],
       [11, 16]])

In [ ]:
# 32.
arr = np.arange(10)
arr1 = arr[arr % 2 ==0]
print(arr1)

[0 2 4 6 8]


In [ ]:
# 33.
arr = np.arange(10)
arr1= arr[arr % 2==1]
arr1

array([1, 3, 5, 7, 9])

In [ ]:
# 34.
arr = np.arange(10)
arr1 = arr[(arr > 3) & (arr < 7)]
arr1

array([4, 5, 6])

In [ ]:
# 35.
arr = np.array([-1, 2, -3, 4])
arr[arr < 0]

array([-1, -3])

In [ ]:
# 36.
arr = np.array([-1, 2, -3, 4])
# abs(arr)
-arr[arr < 0]

array([1, 3])

In [ ]:
# 37.
arr = np.array([-1, 2, -3, 4])
np.where(arr >= 0, arr +10, arr - 10)

array([-11,  12, -13,  14])

In [ ]:
# 38.
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)
arr

[3, 2, 5, 1, 4]

In [ ]:
# 39.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.argmin()

np.int64(0)

In [ ]:
# 40.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.argmax()

np.int64(4)

In [ ]:
# 41.
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [ ]:
# 42.
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack([arr1, arr2])

array([[1, 2],
       [3, 4]])

In [ ]:
# 43.
import numpy as np
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])

In [ ]:
import pandas as pd

In [ ]:
# 44.
from pandas import Series

data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [ ]:
# 45.
data = [100, 200, 300]
index = ['철수', '영희', '아름']
s = Series(data)
s.index = index
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [ ]:
# 46.
from pandas import Series

score = {
    "철수": 100,
    "영희": 200,
    "아름": 300
}

s = Series(score)
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [ ]:
# 47.
st = ["삼성전자", "셀트리온", "카카오", "삼성전자우", "현대바이오"]
str = [73000, 356000, 367000, 68600, 34150]
s = Series(st, str)
print(s)

73000      삼성전자
356000     셀트리온
367000      카카오
68600     삼성전자우
34150     현대바이오
dtype: object


In [ ]:
# 48.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)

s.index

Index(['철수', '영희', '아름'], dtype='object')

In [ ]:
# 49.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.values

array([100, 200, 300])

In [ ]:
# 50.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)

print(s.to_dict())

{'철수': 100, '영희': 200, '아름': 300}


In [ ]:
# 51.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.dtype)

int64


In [ ]:
# 52.
data = [  10,  "가" ]
s = Series( data )
print(s.dtype)

object


In [ ]:
# 53.
data = {
    "2020-12-11" : 73400,
    "2020-12-10" : 72900,
    "2020-12-09" : 73900,
    "2020-12-08" : 71700,
    "2020-12-07" : 72900
}

s = Series(data)
s.name = "종가"
s.index.name = "날짜"
s


날짜
2020-12-11    73400
2020-12-10    72900
2020-12-09    73900
2020-12-08    71700
2020-12-07    72900
Name: 종가, dtype: int64

In [ ]:
# 54.
import pandas as pd

data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s.to_dict()


{'apple': 1500, 'banana': 3000}

In [ ]:
# 55.
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s.index.name = 'icecream'
s


icecream
apple     1500
banana    3000
dtype: int64

In [ ]:
# 56.
s = pd.Series(data=[1, 2, 3])
s.name = 'number'
print(s)

0    1
1    2
2    3
Name: number, dtype: int64


In [ ]:
# 57.
data = [1.0, 2.0, 'NaN']
s = pd.Series(data)
s

0    1.0
1    2.0
2    NaN
dtype: object

In [ ]:
# 58.
s = pd.Series([1, 2, 3])
s1 = np.array(s)
s1

array([1, 2, 3])

In [ ]:
# 59.
s = pd.Series([1, 2, 'python'])
print(s.dtype)


object


In [ ]:
# 60.
s = pd.Series(['1', '2', '3'])
s.astype('int32')

0    1
1    2
2    3
dtype: int32

In [ ]:
# 61.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s['영희']

np.int64(200)

In [ ]:
# 62.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.iloc[1])

200


In [ ]:
# 63.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.loc["영희"]

np.int64(200)

In [ ]:
# 64.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)


print(s.iloc[0:2])
print(s.iloc[ :2])
print(s.loc["철수":"영희"])
print(s[0:2])
print(s[ :2])
print(s["철수":"영희"])
print(s.values[:2])

철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
[100 200]


In [ ]:
# 65.
data = [100, 200, 300, 400, 500, 600]
index = ["08/01", "08/02", "08/03", "08/04", "08/05", "08/06"]
s = Series(data, index)
s.head(3)
# print(s.iloc[0:3].index)

08/01    100
08/02    200
08/03    300
dtype: int64

In [ ]:
# 66.
data = [100, 200, 300, 400, 500, 600] 
index = ["08/01", "08/02", "08/03", "08/04", "08/05", "08/06"] 
s = Series(data, index)

s[[0, 1, 4]]

# print(s.iloc[ : :2])
# print(s[ : :2])

# print(s.loc["08/01":"08/06":2])
# print(s["08/01":"08/06":2])

# print(s.iloc[[0, 2, 4]])
# print(s.iloc[["08/01", "08/03", "08/05"]])


C:\Users\dkreh\AppData\Local\Temp\ipykernel_12980\3299773292.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0, 1, 4]]


08/01    100
08/02    200
08/05    500
dtype: int64

In [ ]:
# 67.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.loc["순이"] = 400
s

철수    100
영희    200
아름    300
순이    400
dtype: int64

In [ ]:
# 68.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)

s= s.drop('철수')
s

영희    200
아름    300
dtype: int64

In [ ]:
# 69.
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s = s.drop("철수", inplace=True)
s

In [ ]:
# 70.
from pandas import Series

data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)
s.unique()

array(['전기,전자', '운수장비', '서비스업'], dtype=object)

In [ ]:
# 71.
import pandas as pd

s = pd.Series(
    data = [9000, 9000, 8000, 9000, 10000],
    index = ['김과장', '이대리', '박전무', '이대리', '이대리']
)
s.unique()

array([ 9000,  8000, 10000])

In [ ]:
# 72.
s = pd.Series(
    data = [9000, 9000, 8000, 9000, 10000],
    index = ['김과장', '이대리', '박전무', '이대리', '이대리']
)
s.index.unique()

Index(['김과장', '이대리', '박전무'], dtype='object')

In [ ]:
# 73.
s = pd.Series(
    data = [9000, 9000, 8000, 9000, 10000],
    index = ['김과장', '이대리', '박전무', '이대리', '이대리']
)
# pd.value_counts(s)
s.value_counts()

9000     3
8000     1
10000    1
Name: count, dtype: int64

In [ ]:
# 74.
s.index.value_counts()

이대리    3
김과장    1
박전무    1
Name: count, dtype: int64

In [ ]:
# 75.
data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)
s.value_counts()

전기,전자    2
서비스업     2
운수장비     1
Name: count, dtype: int64

In [ ]:
# 76.
data = [100, 300, 200]
index = ["08/01", "08/02", "08/03"]
s = Series(data, index)

print(s.iloc[[0, 2, 1]])
print(s.loc[ ["08/01", "08/02", "08/03"]])


08/01    100
08/03    200
08/02    300
dtype: int64
08/01    100
08/02    300
08/03    200
dtype: int64


In [ ]:
# 77.
import numpy as np

data = np.random.randint(10, size=4)
s = Series(data)

s.sort_values()

2    5
0    8
3    8
1    9
dtype: int32

In [ ]:
# 78.
s = Series(np.random.randint(10, size=4), ["b", "c", "a", "d"])
s.sort_index()

a    3
b    1
c    1
d    5
dtype: int32

In [ ]:
# 79.
data = [100, 300, 200]
s = Series(data)

print(s ** 4)

0     100000000
1    8100000000
2    1600000000
dtype: int64


In [ ]:
# 80.
data = [100, 300, 200]
s0 = Series(data, ["a", "b", "c"])
s1 = Series(data, ["a", "c", "b"])
print(s0 + s1)

a    200
b    500
c    500
dtype: int64


In [ ]:
# 81.
high = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
low = Series(data=[50700, 50500, 50500], index=["5/1", "5/2", "5/4"])

diff = high - low
print(diff)

5/1    800.0
5/2    700.0
5/3      NaN
5/4      NaN
dtype: float64


In [ ]:
# 82.
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
qwer = s < 52000
qwer

5/1     True
5/2     True
5/3    False
dtype: bool

In [ ]:
# 83.
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
s[1:]

5/2    51200
5/3    52500
dtype: int64

In [ ]:
# 84.
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
qwer = s <= 52000
print(len(s[qwer]))

2


In [ ]:
# 85, 86, 87.
from pandas import Series 

data = {
    "2020-12-11": 73400,
    "2020-12-10": 72900,
    "2020-12-09": 73900,
    "2020-12-08": 71700,
    "2020-12-07": 72900
}
s = Series(data)

s.sum()
s.mean()
s.max()
s.min()

np.int64(71700)

In [ ]:
# 88.
data = {
    "2020-12-11": 1.01,
    "2020-12-10": 0.99,
    "2020-12-09": 1.03,
    "2020-12-08": 1.02,
    "2020-12-07": 1
}

s = Series(data)
s.product()

np.float64(1.05049494)

In [ ]:
# 89.
import numpy as np
from pandas import Series 

data = [1, 2, 3, 4, np.nan]
s = Series(data)

print(s.isna().sum())

1


In [ ]:
# 90.
data = ["100", "200", "300"]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.astype(np.int32)

철수    100
영희    200
아름    300
dtype: int32

In [ ]:
# 91.
s = pd.Series(["30세", "40세", "50세"], index=["김대리", "이과장", "박차장"])
print(s)
# 김대리    30세
# 이과장    40세
# 박차장    50세
# dtype: object
s1 = s.str[:-1]
s1 = s1.astype('int32')
s1

김대리    30세
이과장    40세
박차장    50세
dtype: object


김대리    30
이과장    40
박차장    50
dtype: int32

In [3]:
# 92.
import numpy as np
from pandas import Series

data = [1, 2, 3, 4, np.nan]
s = Series(data=data)
s
s1 = s.dropna()
print(s1)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64


In [6]:
# 93.
from pandas import Series

data = range(1, 11)
s = Series(data=data)
s
s.nlargest(3)

9    10
8     9
7     8
dtype: int64

In [10]:
# 94.
from pandas import Series

data = range(1, 11)
s = Series(data=data)
s
s.nsmallest(n = 3)

0    1
1    2
2    3
dtype: int64

In [12]:
# 95.
import pandas as pd

data = pd.to_datetime( ['20200101', '20210101', '20220101'] )
s = pd.Series( data)
s.dt.year

0    2020
1    2021
2    2022
dtype: int32

In [14]:
# 96.
import pandas as pd

data = pd.to_datetime( ['20200101', '20210101', '20220101'] )
s = pd.Series( data)
s.dt.day

0    1
1    1
2    1
dtype: int32

In [17]:
# 97.
import pandas as pd

index = pd.to_datetime( ['20200101', '20210101', '20220101'] )
data = [100, 200, 300]
s = pd.Series(data=data, index=index)
s.index.year

Index([2020, 2021, 2022], dtype='int32')

In [22]:
# 98.
import pandas as pd

index = pd.to_datetime( ['20200101', '20210101', '20220101'] )
data = [100, 200, 300]
s = pd.Series(data=data, index=index)
s.index.strftime("%Y-%m-%d 00:00:00")

Index(['2020-01-01 00:00:00', '2021-01-01 00:00:00', '2022-01-01 00:00:00'], dtype='object')

In [24]:
# 99.
import pandas as pd

s = pd.Series(["000020", "000040", "005930"])

'A' + s

0    A000020
1    A000040
2    A005930
dtype: object

In [ ]:
# 100.
import pandas as pd

s = pd.Series(["20", "40", "5930"])
