### PyTorch
- GPU를 이용한 동적 신경망 구축이 가능한 딥러닝 프레임워크

#### PyTorch 구성 요소
- torch : 메인 네임스페이스, 텐서 등의 다양한 함수가 포함
- torch.autograd : 자동 미분 기능을 제공하는 라이브러리
- torch.nn : 신경망 구축을 위한 데이터 구조, 레이어 등을 제공하는 라이브러리
- torch.multiprocessing : 병렬처리 기능을 제공하는 라이브러리
- torch.optim : SGD(확률적 경사 하강법)등 파라미터 최적화 알고리즘 제공
- torch.utils : 데이터 조작 등 유틸리티 기능 제공

#### 01. 텐서(Tensor)
- 방향성과 크기를 동시에 표현하는 다차원 배열

In [1]:
import torch
import numpy as np

torch.__version__

'2.10.0+cpu'

##### 1-1. 텐서의 초기화
- 초기화 : 텐서를 생성하고 특정 값을 (최초로) 채우는 것

##### 초기화 되지 않은 텐서

In [2]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


#### 무작위로 초기화 된 텐서
- rand : 0과 1사이의 값으로 랜덤하게 초기화 된 텐서 생성
- randn : 표준정규분포를 따르는 랜덤한 값으로 초기화

In [3]:
x = torch.rand(4, 2)
y = torch.randn(2, 3)
print(x)
print(y)

tensor([[0.5991, 0.0783],
        [0.9038, 0.1787],
        [0.0530, 0.4393],
        [0.6734, 0.2117]])
tensor([[ 0.8389, -1.4480, -0.8490],
        [ 1.0866,  0.0951,  0.6610]])


#### 0으로 채워진 텐서

In [4]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


#### 1로 채워진 텐서

In [5]:
x = torch.ones(2, 4, dtype=torch.double)
print(x)

# 기존 텐서의 속성(데이터 타입 동일, 장치)을 물려받음
y = x.new_ones(3, 2)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


#### 사용자가 입력한 값으로 텐서 초기화

In [6]:
x = torch.tensor([1, 2.5])
print(x)

tensor([1.0000, 2.5000])


#### Numpy에서 불러오기

In [7]:
data = [1, 2, 3, 4]
np_array = np.array(data)
x = torch.from_numpy(np_array)
print(x)

tensor([1, 2, 3, 4])


#### _like 메서드
- 기존 텐서의 속성을 복사하면서 값만 다른 텐서를 만드는 메서드

In [8]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


##### 1-2. 텐서의 속성

In [ ]:
t = torch.rand(3, 4)
print(t.size()) # 모양
print(t.shape) # 모양
print(t.dtype) # 자료형
print(t.device) # 장치

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu
