### 03. 텐서의 조작

In [1]:
import torch

#### 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [2]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(x[1, 1]) # 5
print(x[2, 0]) # 7
print(x[0, :]) # [1, 2, 3]
print(x[:, 2]) # [3, 6, 9]
print(x[[0, 1, 2], [0, 1, 2]]) # fancy 인덱싱 [1, 5, 9]
print(x[x > 5]) # [6, 7, 8 9]

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [3]:
x = torch.tensor([10, 20, 30, 40, 50])

x[0] = 100
print(x) # [100, 20, 30, 40, 50]

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200, 300, 400])
print(x) # [100, 200, 300, 400, 50]

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


##### 3-2. Tensor의 크기, 모양 변경

- torch.view()

In [9]:
x = torch.randn(4, 5)
print(x)
y = x.view(20)
print(y)
z = y.view(5, -1) # -1 -> 자동 계산
print(z)

n = z.view(2, 2, 5)
print(n)

tensor([[-1.7591,  0.1757, -1.1247,  0.7415, -0.5753],
        [ 0.3466,  0.0221, -0.0856,  1.1163,  2.1006],
        [-0.6744, -0.4239,  0.0490,  0.6924, -0.1208],
        [-0.7348,  0.6377,  0.1876,  0.9153, -0.9262]])
tensor([-1.7591,  0.1757, -1.1247,  0.7415, -0.5753,  0.3466,  0.0221, -0.0856,
         1.1163,  2.1006, -0.6744, -0.4239,  0.0490,  0.6924, -0.1208, -0.7348,
         0.6377,  0.1876,  0.9153, -0.9262])
tensor([[-1.7591,  0.1757, -1.1247,  0.7415],
        [-0.5753,  0.3466,  0.0221, -0.0856],
        [ 1.1163,  2.1006, -0.6744, -0.4239],
        [ 0.0490,  0.6924, -0.1208, -0.7348],
        [ 0.6377,  0.1876,  0.9153, -0.9262]])
tensor([[[-1.7591,  0.1757, -1.1247,  0.7415, -0.5753],
         [ 0.3466,  0.0221, -0.0856,  1.1163,  2.1006]],

        [[-0.6744, -0.4239,  0.0490,  0.6924, -0.1208],
         [-0.7348,  0.6377,  0.1876,  0.9153, -0.9262]]])


##### 3-3. 텐서의 숫자값 얻기
- tensor.item() : 스칼라 값 하나만 존재해야 사용 가능

In [11]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.1309, 0.6239])
tensor(0.1309)
0.1308826208114624


##### 3-4. 차원 축소 및 증가
##### 차원 축소(제거)
- toech.squeeze() : 크기가 1인 차원을 제거함(줄여줌)


In [13]:
x = torch.rand(3, 1, 3)
print(x)
print(x.shape)

y = torch.squeeze(x)
print(y)
print(y.shape)

tensor([[[0.9605, 0.0652, 0.4987]],

        [[0.6115, 0.5665, 0.8827]],

        [[0.1243, 0.1631, 0.3504]]])
torch.Size([3, 1, 3])
tensor([[0.9605, 0.0652, 0.4987],
        [0.6115, 0.5665, 0.8827],
        [0.1243, 0.1631, 0.3504]])
torch.Size([3, 3])


##### 차원 증가(생성)
- torch.unsqueeze() : dim 설정에 따라 차원을 증가시킴
    - dim은 하나의 차원이 추가되는 인덱스

In [18]:
x = torch.rand(3, 3, 3)
print(x)
print(x.shape)

# 0 가장 상위 차원 -> 3 가장 하위 차원
y = torch.unsqueeze(x, dim=0)
print(y)
print(y.shape)

y1 = torch.unsqueeze(x, dim=1)
print(y1.shape)
y2 = torch.unsqueeze(x, dim=2)
print(y2.shape)
y3 = torch.unsqueeze(x, dim=3)
print(y3.shape)

tensor([[[0.3567, 0.7564, 0.3188],
         [0.1794, 0.2809, 0.5251],
         [0.6098, 0.9116, 0.1190]],

        [[0.9596, 0.4716, 0.4961],
         [0.9962, 0.6693, 0.5284],
         [0.6200, 0.6118, 0.0516]],

        [[0.0056, 0.3017, 0.6219],
         [0.0138, 0.5408, 0.7001],
         [0.5908, 0.2793, 0.3738]]])
torch.Size([3, 3, 3])
tensor([[[[0.3567, 0.7564, 0.3188],
          [0.1794, 0.2809, 0.5251],
          [0.6098, 0.9116, 0.1190]],

         [[0.9596, 0.4716, 0.4961],
          [0.9962, 0.6693, 0.5284],
          [0.6200, 0.6118, 0.0516]],

         [[0.0056, 0.3017, 0.6219],
          [0.0138, 0.5408, 0.7001],
          [0.5908, 0.2793, 0.3738]]]])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


##### 3-5. 텐서 간 결합
- torch.stack() : 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원 생성됨

In [20]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.tensor([[9, 10], [11, 12]])
result = torch.stack([x, y, z])
print(result)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


- torch.cat() : 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성 x

In [21]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

result = torch.cat((a, b), dim=1)
print(result)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


##### 3-6. 텐서의 나누기
#####  torch.chunk
- 지정한 개수에 따라 나눔
- 나누어 떨어지지 않는 경우, 마지막 조각이 다른 크기를 가질 수 있음

##### torch.split
- 지정한 사이즈에 따라 나눔
- 나누어 떨어지지 않는 경우, 마지막 조각이 다른 크기를 가질 수 있음

In [23]:
x = torch.rand(3, 7)
print(x)

x1, x2, x3 = torch.chunk(x, 3, dim=1)
print(x1)
print(x2)
print(x3)

tensor([[0.2902, 0.8198, 0.7595, 0.5735, 0.9578, 0.1545, 0.6639],
        [0.6395, 0.3327, 0.3193, 0.2797, 0.2510, 0.6159, 0.0809],
        [0.6853, 0.1301, 0.2903, 0.9988, 0.5949, 0.3257, 0.1883]])
tensor([[0.2902, 0.8198, 0.7595],
        [0.6395, 0.3327, 0.3193],
        [0.6853, 0.1301, 0.2903]])
tensor([[0.5735, 0.9578, 0.1545],
        [0.2797, 0.2510, 0.6159],
        [0.9988, 0.5949, 0.3257]])
tensor([[0.6639],
        [0.0809],
        [0.1883]])


In [24]:
x = torch.rand(3, 7)
print(x)

#  쪼갤 열의 개수 지정
x1, x2, x3 = torch.split(x, [2, 3, 2], dim=1)
print(x1)
print(x2)
print(x3)

tensor([[0.2519, 0.2684, 0.6844, 0.4311, 0.7997, 0.7485, 0.8973],
        [0.7343, 0.1331, 0.3049, 0.2688, 0.4258, 0.5159, 0.4052],
        [0.6927, 0.9987, 0.8984, 0.6512, 0.0771, 0.8361, 0.0974]])
tensor([[0.2519, 0.2684],
        [0.7343, 0.1331],
        [0.6927, 0.9987]])
tensor([[0.6844, 0.4311, 0.7997],
        [0.3049, 0.2688, 0.4258],
        [0.8984, 0.6512, 0.0771]])
tensor([[0.7485, 0.8973],
        [0.5159, 0.4052],
        [0.8361, 0.0974]])
